services:
  universitylink.webapi:
    image: universitylink.webapi
    build:
      context: .
      dockerfile: UniversityLink.WebApi/Dockerfile
    environment:
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ASPNETCORE_HTTP_PORTS=8080